language: node_js
node_js:
- "12"
install:
- npm install -g elm@0.19.1-3
- npm install -g elm-format@0.8.0
- npm install -g elm-test
- elm make
- pushd tests && elm make && popd
- elm-format --validate src/ tests/Tests/
script:
- elm-test
